// <auto-generated />
namespace TaskilyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SurveyUID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SurveyUID));
        
        string IMigrationMetadata.Id
        {
            get { return "201406232104119_SurveyUID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
